export const additionalHeroData = [
  {
    id: "1054",
    name: "Phoenix",
    real_name: "Jean Grey",
    transformations: [
      {
        id: 0,
        icon: "characters/phoenix-headbig-0.webp",
        name: "Phoenix",
        health: "275",
        movement_speed: "6m/s",
      },
    ],
    en_name: "Phoenix",
    description:
      "Original X-Man Jean Grey boasted immense psychic power even before becoming host the unbridled Phoenix Force, embodiment of life and psionic energy across the universe. Now aligned with this ancient cosmic power, Jean and the Phoenix traverse space together, burning bright as both a spark of creation and inferno of destruction!",
    slug: "phoenix",
    team: ["X_men", "Mutants"],
    difficulty: "3",
    attack_type: "Projectile Heroes",
    role: "DUELIST",
    image_square: "characters/phoenix-square.webp",
    image_transverse: "characters/phoenix-transverse.webp",
    icon: "characters/phoenix-headbig.webp",
    image: "characters/phoenix-portrait.webp",
    logo_small: "characters/phoenix-logo.webp",
    logo: "characters/phoenix-logo-small.webp",
    skins: ["1054001"],
    abilities: [
      {
        id: 105411,
        icon: "abilities/1054/105411.webp",
        name: "Cosmic Flames",
        type: "Weapon",
        isCollab: false,
        description:
          "Launch a fiery projectile forward, applying 1 Spark to enemies hit. Critical hits apply 2 Sparks. At 3 Sparks, Phoenix triggers a fiery explosion that applies 1 Spark to enemies around and Healing Over Time to self. Sparks from explosions will not stack within a brief period.",
        additional_fields: {
          Key: "Left Click",
          Damage: "50",
          "Damage Falloff": "Falloff begins at 10m, decreasing to 60% at 30m",
          "Fire Rate": "0.435s per round",
          "Explosion Direct Damage": "40",
          "Explosion Range Damage": "12",
          "Explosion Range": "4m spherical radius spell field",
          "Self Healing Amount after the Explosion": "10/s for 4 s",
        },
        transformation_id: 0,
      },
      {
        id: 105421,
        icon: "abilities/1054/105421.webp",
        name: "Telekinesis Burst",
        type: "Normal",
        isCollab: false,
        description:
          "Mark a targeted area with psionic energy, followed by a series of fiery explosions. The first blast Stuns enemies, while the subsequent two explosions inflict Slow. Applies 1 Spark to enemies hit.",
        additional_fields: {
          Key: "Right Click",
          "Target Explosion Damage": "20",
          "Target Explosion Range": "A cylindrical spell field with a 2m radius and a height of 4m.",
          "Subsequent Explosion Damage": "20",
          "Subsequent Explosion Range": "A cylindrical spell field with a 3m radius and a height of 6m.",
          "Stun Duration": "0.3s",
          "Slow Effect": "Inflict 30% Slow for 2 seconds.",
          Cooldown: "10s",
        },
        transformation_id: 0,
      },
      {
        id: 105431,
        icon: "abilities/1054/105431.webp",
        name: "Dark Ascent",
        type: "Normal",
        isCollab: false,
        description:
          "Merge with the Phoenix, entering a state of free flight. Gain a Movement Boost while continuously replenishing ammunition.",
        additional_fields: {
          Key: "E",
          "Special Effect":
            "Enter a state of free flight within the duration. Gain a 50% Movement Boost and replenish 4 ammo per second.",
          "Maximum Energy": "1200",
          "Energy Cost": "400/s",
          "Energy Recovery": "120/s",
        },
        transformation_id: 0,
      },
      {
        id: 105441,
        icon: "abilities/1054/105441.webp",
        name: "Telepathic Illusion",
        type: "Normal",
        isCollab: false,
        description:
          "Leave behind an illusion and instantly teleport in the desired direction, followed by detonating the illusion. Enemies hit are applied with 1 Spark.",
        additional_fields: {
          Key: "SHIFT",
          "Dash Distance": "8m",
          "Detonation Damage": "50",
          "Detonation Range": "3m spherical radius spell field",
          Cooldown: "12s",
        },
        transformation_id: 0,
      },
      {
        id: 105451,
        icon: "abilities/1054/105451.webp",
        name: "Endsong Inferno",
        type: "Ultimate",
        isCollab: false,
        description:
          "Soar into the sky with the Phoenix and crash down onto a selected area, dealing devastating damage to enemies while creating a shockwave that destroys enemy summons, shields, and any Bonus Health. Enemies hit are applied with 1 Spark.",
        additional_fields: {
          Key: "Q",
          "Energy Cost": "3100",
          "Explosion Damage": "140",
          "Explosion Range": "10m spherical radius spell field",
          "Shockwave Damage": "50",
          "Summons' Health": "400",
          "Self Healing Amount": "250",
        },
        transformation_id: 0,
      },
      {
        id: 105461,
        icon: "abilities/1054/105461.webp",
        name: "Mind's Grace",
        type: "Normal",
        isCollab: true,
        description: "Jean Grey imbues Wolverine with the awe-inspiring Phoenix Force.",
        additional_fields: {
          Key: "Passive",
          "Team-Up Bonus": "10% damage boost",
        },
        transformation_id: 0,
      },
    ],
    meta: [],
  },
];